// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP7ky1_hSbhJ7wsOu2idCbKpV3DHL-ZdA',
    appId: '1:438698346666:android:007c385b0f600c0247a8d3',
    messagingSenderId: '438698346666',
    projectId: 'data-69d8f',
    databaseURL: 'https://data-69d8f-default-rtdb.firebaseio.com',
    storageBucket: 'data-69d8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiICiEc4K9r9Gdn1N5qa-eSXLzQdBfTKA',
    appId: '1:438698346666:ios:17a54e84152a329047a8d3',
    messagingSenderId: '438698346666',
    projectId: 'data-69d8f',
    databaseURL: 'https://data-69d8f-default-rtdb.firebaseio.com',
    storageBucket: 'data-69d8f.appspot.com',
    iosClientId: '438698346666-intsj7asro5e0q5dkp9t272k3dvc8bsm.apps.googleusercontent.com',
    iosBundleId: 'com.example.realtimedatabase',
  );
}
